apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: llm-lora-hpo
  namespace: kubechat
spec:
  objective:
    type: maximize
    goal: 0.90
    objectiveMetricName: eval-bleu
  metricsCollectorSpec:
    source:
      filter:
        metricsFormat:
          - "(eval-bleu)\\s*=\\s*([+-]?\\d*(\\.\\d+)?([Ee][+-]?\\d+)?)"
  algorithm:
    algorithmName: random
  parallelTrialCount: 2
  maxTrialCount: 2
  maxFailedTrialCount: 2
  parameters:
    - name: r
      parameterType: int
      feasibleSpace:
        min: "16"
        max: "64"
        step: "32"
    # - name: alpha
    #   parameterType: int
    #   feasibleSpace:
    #     min: "8"
    #     max: "12"
    - name: dropout
      parameterType: double
      feasibleSpace:
        min: "0.1"
        max: "0.3"
        step: "0.1"
    # - name: targetModules
    #   parameterType: categorical
    #   feasibleSpace:
    #     list:
    #       - '["q_proj","v_proj"]'
    #       - '["q_proj","k_proj","v_proj","o_proj"]'
    #       - '["q_proj","k_proj","v_proj","o_proj","gate_proj","down_proj","up_proj"]'
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: loraR
        reference: r
      # - name: loraAlpha
      #   reference: alpha
      - name: loraDropout
        reference: dropout
      # - name: loraTargetModules
      #   reference: targetModules
    
    # trailSpec is defined in katib_train_op.py file