apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-katib-experiment-watcher
  namespace: kubechat
subjects:
  - kind: ServiceAccount
    name: default-editor
    namespace: kubechat
roleRef:
  kind: Role
  name: katib-experiment-watcher
  apiGroup: rbac.authorization.k8s.io
