apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: katib-experiment-watcher
  namespace: kubechat
rules:
  - apiGroups: ["kubeflow.org"]
    resources:
      - experiments
      - experiments/status
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
