apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: llm-lora-hpo
  namespace: kubechat
spec:
  objective:
    type: maximize
    goal: 0.90
    objectiveMetricName: eval-bleu
  metricsCollectorSpec:
    source:
      filter:
        metricsFormat:
          - "(eval-bleu)\\s*=\\s*([+-]?\\d*(\\.\\d+)?([Ee][+-]?\\d+)?)"
  algorithm:
    algorithmName: random
  parallelTrialCount: 2
  maxTrialCount: 2
  maxFailedTrialCount: 2
  parameters:
    - name: r
      parameterType: int
      feasibleSpace:
        min: "4"
        max: "8"
    # - name: alpha
    #   parameterType: int
    #   feasibleSpace:
    #     min: "8"
    #     max: "12"
    - name: dropout
      parameterType: double
      feasibleSpace:
        min: "0.1"
        max: "0.3"
        step: "0.1"
    # - name: targetModules
    #   parameterType: categorical
    #   feasibleSpace:
    #     list:
    #       - '["q_proj","v_proj"]'
    #       - '["q_proj","k_proj","v_proj","o_proj"]'
    #       - '["q_proj","k_proj","v_proj","o_proj","gate_proj","down_proj","up_proj"]'
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: loraR
        reference: r
      # - name: loraAlpha
      #   reference: alpha
      - name: loraDropout
        reference: dropout
      # - name: loraTargetModules
      #   reference: targetModules
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata: 
            annotations: 
              "sidecar.istio.io/inject": "false"
          spec:
            serviceAccountName: default-editor
            containers:
              - name: training-container
                image: mlops-training:latest  # Replace with your actual image URI
                imagePullPolicy: IfNotPresent
                command:
                  - "python"
                  - "/app/train.py"
                  - "--training_dataset_path=/data/1/39b5f705b7214c869504eb46e0105068/artifacts/dataset/train.parquet"
                  - "--output_model_dir=/data/model/"
                  - "--lora_r=${trialParameters.loraR}"
                  # - "--lora_alpha=${trialParameters.loraAlpha}",
                  - "--lora_dropout=${trialParameters.loraDropout}"
                  # - "--lora_target_modules=${trialParameters.loraTargetModules}"
                  - "--test_run"
                # resources:
                #   limits:
                #     memory: "1Gi"
                #     cpu: "0.5"
                envFrom:
                  - configMapRef:
                      name: common-config
                volumeMounts:
                  - mountPath: /data
                    name: shared-storage
            volumes:
            - name: shared-storage
              persistentVolumeClaim:
                claimName: shared-pvc
            restartPolicy: Never