apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: kube-chat
  labels:
    app: mlflow-server
spec:
  selector:
    app: mlflow-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP