name: train
description: Download Dataset OP for downloading dataset and saving dataset as artifact in MLflow.

inputs:
  - name: train_dataset_path
    type: String
    description: Dataset Artifact URI
  - name: hpo_result
    type: String
    description: 'LoRA rank'

outputs:
  - name: output_model_dir
    type: String
    description: Directory for model to save

implementation:
  container:
    image: kubechat-train:latest
    command:
      - python
      - train.py
      - --train
      - --test_run
    args:
      - --train_dataset_path
      - {inputValue: train_dataset_path}
      - --output_model_dir
      - {outputPath: output_model_dir}
      - --hpo_result
      - {inputValue: hpo_result}

      