
name: Component-based Docker Build and Push
on:
  push:
    branches:
      - develop


env:
  # using minikube docker
  DOCKER_TLS_VERIFY: 1
  DOCKER_HOST: tcp://192.168.49.2:2376
  DOCKER_CERT_PATH: /home/mnehete32/.minikube/certs
  MINIKUBE_ACTIVE_DOCKERD: kube

  # added as env variable in ci/cd action runners
  # KUBEFLOW_API_URL: http://kubeflow.nehete.com/pipeline/

  # images
  DOWNLOAD_DATASET_IMAGE: kubechat-download-dataset:${{ github.sha }}
  DATA_PREP_IMAGE: kubechat-data-preparation:${{ github.sha }}
  TRAIN_TEST_SPLIT_IMAGE: kubechat-train-test-split:${{ github.sha }}
  TRAINING_IMAGE: kubechat-training:${{ github.sha }}
  TESTING_IMAGE: kubechat-testing:${{ github.sha }}
  HPO_IMAGE: kubechat-hpo:${{ github.sha }}
  MLFLOW_IMAGE: kubechat-mlflow:latest



jobs:
  build_and_push_components:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # --- Data Preparation Component ---
      - name: Build and Push Download Dataset Docker Image
        run: |
          docker build -t $DOWNLOAD_DATASET_IMAGE .
          # docker push $DOWNLOAD_DATASET_IMAGE
        working-directory: components/download_dataset/

      # --- Data Preparation Component ---
      - name: Build and Push Data Preparation Docker Image
        run: |
          docker build -t $DATA_PREP_IMAGE .
          # docker push $DATA_PREP_IMAGE
        working-directory: components/data_prep/

      # --- Train Test Split Component ---
      - name: Build and Push Train Test Split Docker Image
        run: |
          docker build -t $TRAIN_TEST_SPLIT_IMAGE .
          # docker push $TRAIN_TEST_SPLIT_IMAGE
        working-directory: components/train_test_split/

      # --- Testing Component ---
      - name: Build and Push Hyperparamter optimization Docker Image
        run: |
          docker build -t $HPO_IMAGE .
          # docker push $HPO_IMAGE
        working-directory: components/hpo/

      # --- Training Component ---
      - name: Build and Push Training Docker Image
        run: |
          docker build -t $TRAINING_IMAGE .
          # docker push $TRAINING_IMAGE
        working-directory: components/training/
      
      # --- Testing Component ---
      - name: Build and Push Testing Docker Image
        run: |
          docker build -t $TESTING_IMAGE .
          # docker push $TESTING_IMAGE
        working-directory: components/testing/

      - name: Build and Push MLFLOW Docker Image
        run: |
          docker build -t  $MLFLOW_IMAGE .
          # docker push $MLFLOW_IMAGE
        working-directory: kube/mlflow/


  create_kube_resources:
    needs: build_and_push_components
    runs-on: [self-hosted, linux, x64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Create resources
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
        KUBE_CLUSTER_NAME: ${{ secrets.KUBE_CLUSTER_NAME }}
      run: |
        kubectl config use-context $KUBE_CLUSTER_NAME
        kubectl apply -k kube/

  run_pipeline:
    needs: create_kube_resources
    runs-on: [self-hosted, linux, x64]      
    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.4
        
    - name: Run pipeline
      env:
        PIPELINE_NAME: ${{ vars.PIPELINE_NAME }}
        NAMESPACE: ${{ vars.NAMESPACE }}
        EXPERIMENT_NAME: ${{ vars.EXPERIMENT_NAME }}
        USER_NAME: ${{ secrets.USER_NAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        KUBEFLOW_API_URL: ${{ vars.KUBEFLOW_API_URL }}
        GITHUB_SHA: ${{ github.sha }}
      run: |
        pip install -r 'requirements.txt'
        python pipeline.py 